# Generated by Django 5.1.6 on 2025-03-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
