# Generated by Django 5.1.6 on 2025-03-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.CharField(default='HTML', max_length=255),
        ),
    ]
