# Generated by Django 5.1.6 on 2025-03-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_remove_user_blocked_users_user_blocked_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JavaScript')], max_length=50, unique=True)),
                ('users', models.ManyToManyField(blank=True, related_name='tags', to='connect.user')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
    ]
