# Generated by Django 5.1.6 on 2025-03-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_remove_user_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JavaScript'), ('Python', 'Python'), ('Django', 'Django')], max_length=50, unique=True),
        ),
    ]
