# Generated by Django 5.1.6 on 2025-03-04 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_alter_tag_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
    ]
