# Generated by Django 5.1.6 on 2025-03-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_alter_user_managers_user_date_joined_user_first_name_and_more'),
        ('connect', '0009_rename_tag_tags'),
    ]

    operations = [
    ]
