# Generated by Django 5.1.6 on 2025-03-06 15:49

import connect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0013_comment_dislikes_comment_likes_post_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_username',
            field=models.CharField(default=connect.models.generate_random_username, max_length=150),
        ),
    ]
