# Generated by Django 5.1.6 on 2025-03-06 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0014_user_random_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='liketrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('commentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liketrackcommentid', to='connect.post')),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liketrackpostid', to='connect.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liketracksuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
