# Generated by Django 5.1.6 on 2025-03-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0016_alter_liketrack_commentid_alter_liketrack_postid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='liketrack',
            table='liketrack',
        ),
    ]
