# Generated by Django 5.1.6 on 2025-03-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0017_alter_liketrack_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='liketrack',
            name='dislikes',
            field=models.BooleanField(default=False),
        ),
    ]
