# Generated by Django 5.1.6 on 2025-03-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0018_liketrack_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liketrack',
            name='commentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liketrackcommentid', to='connect.comment'),
        ),
    ]
