# Generated by Django 5.1.6 on 2025-03-13 16:10

import connect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0019_alter_liketrack_commentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default=connect.models.user_profile_picture_path, null=True, upload_to=connect.models.user_profile_picture_path),
        ),
    ]
